# -*- coding: utf-8 -*-

SYNC_LOCAL_NEW = "SYNC_LOCAL_NEW"
SYNC_LOCAL_MODIFIED = "SYNC_LOCAL_MODIFIED"
SYNC_LOCAL_MOVED = "SYNC_LOCAL_MOVED"
SYNC_LOCAL_DELETED = "SYNC_LOCAL_DELETED"
SYNC_LOCAL_REVERT = "SYNC_LOCAL_REVERT"

WATCHDOG_FILE_CHANGED = "WATCHDOG_FILE_CHANGED"



